"""Add image_url and analysis to Outfit model

Revision ID: 1f9527f28c6b
Revises: 
Create Date: 2025-05-20 16:03:01.817434

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f9527f28c6b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('outfit', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('analysis', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('outfit', schema=None) as batch_op:
        batch_op.drop_column('analysis')
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###
